### ISSUE TITLE
jcifs.smb.SmbException: The system cannot find the path specified after upgrade to jcifs-ng 2.0.8 (from 1.5.3)

### ISSUE THREAD

**Issue by johannes-martin** [AgNO3/jcifs-ng#134]
I've got a small sample program:

```
import jcifs.smb.SmbFile;

public class TestSmbFile {
    public static void main(String args[]) throws Exception {
	SmbFile[] files = new SmbFile(args[0]).listFiles();
	for (SmbFile file : files) {
	    System.out.println(file.getPath() + (file.exists() ? " exists" : " does not exist"));
	}
    }
}

```

If I run it with jcifs-ng 1.5.3 using
java -cp .... TestSmbFile smb://domain;user:pass@server/dfs/shares/someshare/path/
it lists the contents of the directories and confirms that every file in there exists.

If I run the same program with identical parameters with jcifs-ng 2.0.8 it throws an exception:

> Exception in thread "main" jcifs.smb.SmbException: The system cannot find the path specified.
        at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1413)
        at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1524)
        at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:984)
        at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1495)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:400)
        at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:465)
        at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
        at jcifs.smb.DirFileEntryEnumIterator2.open(DirFileEntryEnumIterator2.java:94)
        at jcifs.smb.DirFileEntryEnumIteratorBase.<init>(DirFileEntryEnumIteratorBase.java:67)
        at jcifs.smb.DirFileEntryEnumIterator2.<init>(DirFileEntryEnumIterator2.java:56)
        at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:227)
        at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
        at jcifs.smb.SmbFile.listFiles(SmbFile.java:1179)
        at TestSmbFile.main(TestSmbFile.java:5)
  
The same problem occurs if I test for existance of some file without listing directories first.

Strangely, in my real world program, a second call to file.exists() immediately following the first call sometimes succeeds (but not in a small test case I wrote).

jcifs-ng 2.1.1 quits even earlier, reporting 

> Exception in thread "main" jcifs.smb.SmbException: The system cannot find the path specified.
        at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1413)
        at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1524)
        at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:984)
        at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1495)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:400)
        at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:465)
        at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
        at jcifs.smb.DirFileEntryEnumIterator2.open(DirFileEntryEnumIterator2.java:94)
        at jcifs.smb.DirFileEntryEnumIteratorBase.<init>(DirFileEntryEnumIteratorBase.java:67)
        at jcifs.smb.DirFileEntryEnumIterator2.<init>(DirFileEntryEnumIterator2.java:56)
        at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:227)
        at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
        at jcifs.smb.SmbFile.listFiles(SmbFile.java:1179)
        at TestSmbFile.main(TestSmbFile.java:5)

**Comment by johannes-martin** [comment]
Attached is a maven project along with trace level output from running the sample program with jcifs-1.5.3, 2.0.8, and 2.1.1.

Will this help to find the problem?

The logs for 2.0.8 and 2.1.1 both say "smb://domain;user:password@domain.intra.loc/dfs/home/user/dummy/". How would I release a directory?

[issue-134.zip](https://github.com/AgNO3/jcifs-ng/files/2803370/issue-134.zip)

**Comment by mbechler** [comment]
Sorry for the delay.

For 2.0.8 the DFS referral seems to be correctly found but the path not replaced properly before making the request. I think this is the case because the actual target share is reported with the DFS flag, which the logic did not consider (my servers don't appear to set that in this case). I commited a patch that might fix that.

For 2.1.1 there is also "Server does not support basic NTLM signature key exchange": This is the result of some SPNEGO/NTLM hardening in 2.1 (more details in #135), what kind of servers are these?

**Comment by johannes-martin** [comment]
> For 2.1.1 there is also "Server does not support basic NTLM signature key exchange": This is the result of some SPNEGO/NTLM hardening in 2.1 (more details in #135), what kind of servers are these?

Our name space servers run Windows Server 2012 R2 Standard Version 6.3.9600.

**Comment by mbechler** [comment]
Okay, then this is definitely a bug... I think I fixed that in master now.

**Comment by rconoverq** [comment]
I am running into what appears to be the same bug.  What release will the fix mentioned above be available in?  I am using 2.1.2

**Comment by mbechler** [comment]
Which of the issues? The fixes should be in 2.1.2, so you might encounter a different issue, please open a separate issue nad provide more details (debug log, packet trace).

**Comment by rconoverq** [comment]
After further investigation I had an error in my code that dropped the separator between path and file name.  Thanks, for the reply.

**Comment by johannes-martin** [comment]
I've only now had the chance to test this again. The "Server does not support basic NTLM signature key exchange" is now gone, but I still get the "The system cannot find the path specified.". I'm attaching an updated log.
[issue-134.zip](https://github.com/AgNO3/jcifs-ng/files/3227735/issue-134.zip)

**Comment by mbechler** [comment]
So as far as I can tell what happens is:
- Resolving the domain based DFS roots in advance fails as the domain controller is not DFS capable.
- The referral is correctly determined, a connection to the correct share is made
- The share is marked DFS capabable, in comination with 1. this means that no client side resolving of the path is done and the full request path is sent.
- Full request path is used, but somehow seems to be missing the SMB2_FLAGS_DFS_OPERATIONS

Unfortunately I haven't found the reason for the flag missing, I've added some additional debugging code master, could you give this another try? 

>  DEBUG ateRequest: Opening omain.intra.loc\dfs\home\user\dummy
The name here has been truncated in your editing, right?

**Comment by johannes-martin** [comment]
Thanks a lot for looking into this. I've run the test case with the code from master and will attach it to this issue.

The truncating of class names in the log was caused by the log4j configuration. I've changed that now to show the complete class name.
[issue-134.zip](https://github.com/AgNO3/jcifs-ng/files/3246071/issue-134.zip)

**Comment by johannes-martin** [comment]
I tried with the released version of 2.1.3... unfortunately I still get the same error. Any chance of finding the cause of the problem?

**Comment by vchatchai** [comment]
I found this problem also.
I try to create folder 2 kinds it throw sam exception.

private void getCIFFolder1(SmbResource file, List<SmbFile> cifFolders) throws MalformedURLException, CIFSException {
        // SmbResource file = getFile(path);

        if (file.exists() && file.isDirectory()) {

            while (file.children().hasNext()) {
                SmbResource children = file.children().next();
                if (documentsFolder.contains(children.getName())) {
                    // cifFolders.add(file);
                    break;
                } else {
                    while (children.children().hasNext()) {

                        SmbResource children2 = children.children().next();
                        while (children2.children().hasNext()) {

                            SmbResource children3 = children2.children().next();

                            System.out.println(children3.getName());

                        }

                    }
                    // getCIFFolder(children, cifFolders);

                }
            }
        }
    }

    private void getCIFFolder2(SmbFile file, List<SmbFile> cifFolders) throws SmbException, MalformedURLException {
        if (!file.isFile()) {
            SmbFile[] smbFiles = file.listFiles();
            for (SmbFile folder : smbFiles) {
                if (documentsFolder.contains(folder)) {
                    cifFolders.add(file);
                    break;
                } else {
                    SmbFile smbFile = new SmbFile(folder.getURL(), cifsContext);
                    boolean value = smbFile.isFile();
                    if (!value) {
                        getCIFFolder2(smbFile, cifFolders);
                    }
                }
            }
        }
    }

**Comment by vchatchai** [comment]
jcifs.smb.SmbException: The system cannot find the file specified.
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1441) ~[jcifs-2.1.6.jar:na]
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1552) ~[jcifs-2.1.6.jar:na]
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007) ~[jcifs-2.1.6.jar:na]
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523) ~[jcifs-2.1.6.jar:na]
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:407) ~[jcifs-2.1.6.jar:na]
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472) ~[jcifs-2.1.6.jar:na]
	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399) ~[jcifs-2.1.6.jar:na]
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314) ~[jcifs-2.1.6.jar:na]
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294) ~[jcifs-2.1.6.jar:na]
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130) ~[jcifs-2.1.6.jar:na]
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117) ~[jcifs-2.1.6.jar:na]
	at jcifs.smb.DirFileEntryEnumIterator2.open(DirFileEntryEnumIterator2.java:94) ~[jcifs-2.1.6.jar:na]
	at jcifs.smb.DirFileEntryEnumIteratorBase.<init>(DirFileEntryEnumIteratorBase.java:67) ~[jcifs-2.1.6.jar:na]
	at jcifs.smb.DirFileEntryEnumIterator2.<init>(DirFileEntryEnumIterator2.java:56) ~[jcifs-2.1.6.jar:na]
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:227) ~[jcifs-2.1.6.jar:na]
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283) ~[jcifs-2.1.6.jar:na]
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1191) ~[jcifs-2.1.6.jar:na]

**Comment by joachim-roth** [comment]
I had a similar looking issue which was finally solved by adding a trailing "/" to the path (as mentioned in javadoc)
Before, when we listed files we saw:
`SmbFile directory = new SmbFile("smb://server/share/dir1/dir2);
SmbFile[] files = directory.listFiles();
System.out.println(files[0].getName());`
Would result in _smb://server/share/dir1/file1_, not reflecting dir2 anymore in the path, but beeing the filename of a member of dir2.
Solution: add the **/** at the end of the directory
`SmbFile directory = new SmbFile("smb://server/share/dir1/dir2/);
SmbFile[] files = directory.listFiles();
System.out.println(files[0].getName());`
Results in proper, full paths. This took me to long.

**Comment by mbechler** [comment]
Sorry, lost track of the issue. Unfortunately, even with the added debugging I don't get where the flag is dropped. _SmbTree.send_ definitely calls _setResolveInDfs_ and the flag is gone when the request is encoded. I don't see anything changing the flags. Can you run the test in a debugger with a breakpoint on the _jcifs.internal.smb2.ServerMessageBlock2.flags_ field?


@vchatchai, please open a sepeare ticket with more details (at least debug log), this can be many things.

@joachim-roth: Good catch, I really think we should clean up that behavior, we should be able to make everything work without requring the trailing slash, but this change has to go in a major version.

**Comment by johannes-martin** [comment]
@mbechler: I set a breakpoint as suggested (in NetBeans) and made it print the contents of the flags field for every access and change.

[debugger-console.txt](https://github.com/AgNO3/jcifs-ng/files/5001840/debugger-console.txt)

I'm not sure how helpful this is... Let me know if I can improve this somehow.

**Comment by brunnels** [comment]
Just wanted to report I ran into this same issue and adding a trailing slash to my share path resolved the issue for me.
