### ISSUE TITLE
User session deleted when processing large data using SMB3

### ISSUE THREAD

**Issue by jmagesh** [AgNO3/jcifs-ng#242]
When attempting to read 100+ large (~500 MB) files using SMB3 after about an hour or so, the user session gets deleted (NT_STATUS_USER_SESSION_DELETED 0xc0000203).
We did not have this problem with SMB2.

Data source CIFS Server:
Windows Server 2016 Standard - supports SMB 3.1.1
Local security options

Microsoft network server: Digitally sign communications (always) - Enabled
Microsoft network server: Digitally sign communications (if client agrees) - Enabled

jcifs.properties:
jcifs.smb.client.minVersion=SMB302
jcifs.smb.client.maxVersion=SMB311
jcifs.smb.client.signingPreferred=true
jcifs.smb.client.signingEnforced=true
jcifs.smb.client.ipcSigningEnforced=true
jcifs.smb.client.dfs.disabled=false

`jcifs.smb.SmbException: An unexpected network error, user session deleted, occurred.
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1462) ~[jcifs-ng-2.1.4-flx.1.jar:?]
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1573) ~[jcifs-ng-2.1.4-flx.1.jar:?]
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1028) ~[jcifs-ng-2.1.4-flx.1.jar:?]
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1544) ~[jcifs-ng-2.1.4-flx.1.jar:?]
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409) ~[jcifs-ng-2.1.4-flx.1.jar:?]
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472) ~[jcifs-ng-2.1.4-flx.1.jar:?]
	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:410) ~[jcifs-ng-2.1.4-flx.1.jar:?]
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:324) [jcifs-ng-2.1.4-flx.1.jar:?]
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:304) [jcifs-ng-2.1.4-flx.1.jar:?]
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130) [jcifs-ng-2.1.4-flx.1.jar:?]
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117) [jcifs-ng-2.1.4-flx.1.jar:?]
	at jcifs.smb.SmbFile.withOpen(SmbFile.java:1792) [jcifs-ng-2.1.4-flx.1.jar:?]
	at jcifs.smb.SmbFile.withOpen(SmbFile.java:1761) [jcifs-ng-2.1.4-flx.1.jar:?]
	at jcifs.smb.SmbFile.withOpen(SmbFile.java:1755) [jcifs-ng-2.1.4-flx.1.jar:?]
	at jcifs.smb.SmbFile.queryPath(SmbFile.java:807) [jcifs-ng-2.1.4-flx.1.jar:?]
	at jcifs.smb.SmbFile.exists(SmbFile.java:890) [jcifs-ng-2.1.4-flx.1.jar:?]
	at jcifs.smb.SmbFile.lastModified(SmbFile.java:1152) [jcifs-ng-2.1.4-flx.1.jar:?]
`

If more details are needed, please let me know.

Thanks.

**Comment by mbechler** [comment]
Can you identify any more specific conditions, e.g. message id or amount of transferred data? Maybe the server log also reveals why the session is invalidated.
For "normal" session expiration I would expect a STATUS_NETWORK_SESSION_EXPIRED (0xC000035C) error so I would guess this is something different.

We probably could do the same thing as for SESSION_EXPIRED and just establish a new session when it occurs, however its always nice to figure out why someething like this happens in the first place.

**Comment by jmagesh** [comment]
The error ID was 0xc0000203 (is that what you meant by message ID?).
The amount of transferred data varied. Sometimes it was about 3.3 GB, other times it was 8.5 GB.
The server log didn't reveal anything unusual but we suspect that something needs to be set on the server to prevent this user session from being deleted.
We did try creating a new session but that didn't help. The error still occurred.
We did figure out a workaround that worked -- setting the `jcifs.smb.client.ssnLimit=1` in `jcifs.properties` prevented the error from occurring. We are unsure if there are any performance implications of doing this (we didn't observer any) but a better solution would be preferable.

**Comment by jmagesh** [comment]
Network capture attached.

[status_user_session_deleted.zip](https://github.com/AgNO3/jcifs-ng/files/5120704/status_user_session_deleted.zip)

You're right. This may not be an issue specific to SMB3.

Let me know if you need anything else.

Thanks.

**Comment by mbechler** [comment]
Sorry for the delay. This looks like for some reason it is reusing an old connection. 
Unfortunately the trace does not include what happened with that connection before and neither can I see a reason for the connection not being reused. Are you using multiple contexts/different users? 

A complete debug log would be helpful, however a full log will probably get excessively large. I guess the minimal useful logging configuration would be DEBUG on 

jcifs.smb.SmbSessionImpl
jcifs.smb.SmbTransportPoolImpl
jcifs.smb.SmbTransportImpl



A possible problem in this situtation could be session timeout from the client side (+ a bug that does not properly track the session state), which could likely be avoided by setting _jcifs.smb.client.sessionTimeout=0_.

**Comment by jmagesh** [comment]
[smb.tar.gz](https://github.com/AgNO3/jcifs-ng/files/5285254/smb.tar.gz)
Logs with log level DEBUG attached. Hope they help determine if an old connection is in play.

We do use multiple (generally 4) processes to access the data (concurrently) but they all use the same user account.

We did try setting the client session timeout to 0 but that didn't work for us consistently.
If you need anything else please let me know.

**Comment by mbechler** [comment]
smb3.out:
```
[2020-09-24 19:31:53,354] DEBUG [Transport2] jcifs.smb.SmbTransportImpl Disconnecting transport while still in use Transport2[0.0.0.0<00>/XXX.XXX.XXX.XXX:445,state=5,signingEnforced=true,usage=3]: [SmbSession[credentials=domain\user,targetHost=XXX.XXX.XXX.XXX,targetDomain=null,uid=0,connectionState=2,usage=2]]
[2020-09-24 19:31:53,354] DEBUG [Transport2] jcifs.smb.SmbTransportImpl Disconnecting transport Transport2[0.0.0.0<00>/XXX.XXX.XXX.XXX:445,state=5,signingEnforced=true,usage=3]
[2020-09-24 19:31:53,354] DEBUG [Transport2] jcifs.smb.SmbSessionImpl Logging off session on Transport2[0.0.0.0<00>/XXX.XXX.XXX.XXX:445,state=5,signingEnforced=true,usage=4]
[2020-09-24 19:31:53,354] DEBUG [Transport2] jcifs.smb.SmbSessionImpl Logging off session while still in use SmbSession[credentials=domain\user,targetHost=XXX.XXX.XXX.XXX,targetDomain=null,uid=0,connectionState=3,usage=2]:[SmbTree[share=SHARE,service=null,tid=1,inDfs=false,inDomainDfs=false,connectionState=2,usage=0], SmbTree[share=IPC$,service=null,tid=5,inDfs=false,inDomainDfs=false,connectionState=2,usage=0]]
[2020-09-24 19:31:53,355] DEBUG [Transport2] jcifs.smb.SmbSessionImpl Disconnect tree on logoff
[2020-09-24 19:31:53,355] DEBUG [Transport2] jcifs.smb.SmbSessionImpl Disconnect tree on logoff
[2020-09-24 19:31:53,355] DEBUG [Transport2] jcifs.smb.SmbTransportPoolImpl Scheduling transport connection for removal Transport2[0.0.0.0<00>/XXX.XXX.XXX.XXX:445,state=5,signingEnforced=true,usage=3] (-426618911)
```

smb4.out:
```
[2020-09-24 19:16:42,709] DEBUG [Transport2] jcifs.smb.SmbTransportImpl Compound next command 0 read size 128 remain 128
[2020-09-24 19:17:01,243] DEBUG [Transport3] jcifs.smb.SmbTransportImpl Disconnecting transport Transport3[domain/XXX.XXX.XXX.XXX:445,state=5,signingEnforced=true,usage=0]
[2020-09-24 19:17:01,243] DEBUG [Transport3] jcifs.smb.SmbSessionImpl Logging off session on Transport3[domain/XXX.XXX.XXX.XXX:445,state=5,signingEnforced=true,usage=1]
[2020-09-24 19:17:01,244] DEBUG [Transport3] jcifs.smb.SmbSessionImpl Disconnect tree on logoff
[2020-09-24 19:17:01,244] DEBUG [Transport3] jcifs.smb.SmbSessionImpl Reacquire transport
[2020-09-24 19:17:01,249] DEBUG [Transport3] jcifs.smb.SmbSessionImpl Usage dropped to zero, release connection Transport3[domain/XXX.XXX.XXX.XXX:445,state=5,signingEnforced=true,usage=2]
[2020-09-24 19:17:01,250] DEBUG [Transport3] jcifs.smb.SmbTransportPoolImpl Scheduling transport connection for removal Transport3[domain/XXX.XXX.XXX.XXX:445,state=5,signingEnforced=true,usage=0] (1650914356)
[2020-09-24 19:17:01,293] DEBUG [Transport4] jcifs.smb.SmbTransportImpl Disconnecting transport Transport4[hostname/XXX.XXX.XXX.XXX:445,state=5,signingEnforced=true,usage=0]
[2020-09-24 19:17:01,293] DEBUG [Transport4] jcifs.smb.SmbSessionImpl Logging off session on Transport4[hostname/XXX.XXX.XXX.XXX:445,state=5,signingEnforced=true,usage=1]
[2020-09-24 19:17:01,293] DEBUG [Transport4] jcifs.smb.SmbSessionImpl Disconnect tree on logoff
[2020-09-24 19:17:01,294] DEBUG [Transport4] jcifs.smb.SmbSessionImpl Reacquire transport
[2020-09-24 19:17:01,295] DEBUG [Transport4] jcifs.smb.SmbSessionImpl Usage dropped to zero, release connection Transport4[hostname/XXX.XXX.XXX.XXX:445,state=5,signingEnforced=true,usage=2]
[2020-09-24 19:17:01,295] DEBUG [Transport4] jcifs.smb.SmbTransportPoolImpl Scheduling transport connection for removal Transport4[hostname/XXX.XXX.XXX.XXX:445,state=5,signingEnforced=true,usage=0] (-2101520205)
[2020-09-24 19:32:31,345] DEBUG [Transport2] jcifs.smb.SmbTransportImpl Compound next command 0 read size 80 remain 80
[2020-09-24 19:32:31,346] DEBUG [-1147151260@qtp--564857684-1] jcifs.smb.SmbTransportImpl Error code: 0xC0000203 for Smb2CreateRequest
[2020-09-24 19:32:31,363] DEBUG [Transport2] jcifs.smb.SmbTransportImpl Compound next command 0 read size 80 remain 80
[2020-09-24 19:32:31,363] DEBUG [-1147151260@qtp--564857684-1] jcifs.smb.SmbTransportImpl Error code: 0xC0000203 for Smb2CreateRequest

```

This very much looks like the connection is forcibly closed while there are still objects relying on a session on it. Unless you are explicitly closing it yourself (e.g. closing the context would do that), this should only occur when some serious error occurs.

I think there is a chance that an exception could be swallowed in jcifs.util.transport.Transport.loop(), for example the remote could be closing the connection or an unexpected socket level timeout occurs. 
Unfortunately that class did not yet contain suitable logging, so I added some in master.

Sorry for all the back and forth, but could you get a log for jcifs.util.transport.Transport using the current master as well?

**Comment by jmagesh** [comment]
Thanks for adding the logging. I updated the code and re-ran the test. Here are the logs.
[smb.tar.gz](https://github.com/AgNO3/jcifs-ng/files/5359621/smb.tar.gz)

As far as I can tell, we aren't closing the context or the connection ourselves.

**Comment by mbechler** [comment]
Unfortunately, this time I don't see a disconnect or any other reasons for the failures to start. Likely will need more complete logs to try figure out what is happening.  Judging from the logs so far, about 1 minute before the errors start appearing would be should be sufficient. Can you provide full debug logs for that?

**Comment by jmagesh** [comment]
Here's a log with level set to 'trace'. Hope it provides enough information.
[smb3.tar.gz](https://github.com/AgNO3/jcifs-ng/files/5362408/smb3.tar.gz)
If you need anything else, please let me know. Thanks.

**Comment by jmagesh** [comment]
Hi @mbechler, was the log of any help in identifying why the connection might be being closed prematurely? For example, is it something on the server or on the client?
What sort of commands might close the context?

**Comment by mbechler** [comment]
Judging from the log there is no interaction between the client and the server between the last succesful request on that connection and session and the one 6 minutes later when it then fails.

So, there seems to be nothing that would close the session from the client side and I guess this only leaves some kind of server side timeout. 

As metioned before this is not the expected error code for a session, but we can try to handle it as such and see what happens. I've commited some code that should do just that.



```
[2020-10-11 17:49:10,939] TRACE [Transport2] jcifs.smb.SmbTransportImpl New data read: Transport2[0.0.0.0<00>/XXX.XXX.XXX.XXX:445,state=3,si
gningEnforced=true,usage=5]
[2020-10-11 17:49:10,939] TRACE [Transport2] jcifs.smb.SmbTransportImpl FE534D4240000000000000000500000009000000980000001D26010000000000
[2020-10-11 17:49:10,939] DEBUG [Transport2] jcifs.smb.SmbTransportImpl Compound next command 72 read size 72 remain 200
[2020-10-11 17:49:10,939] DEBUG [Transport2] jcifs.smb.SmbTransportImpl Compound next command 0 read size 128 remain 128
[2020-10-11 17:49:10,939] TRACE [48035149@qtp--1026970421-0] jcifs.smb.SmbTransportImpl Response is command=SMB2_CREATE,status=0,flags=0x000
9,mid=75293,wordCount=0,byteCount=0
[2020-10-11 17:49:10,939] TRACE [48035149@qtp--1026970421-0] jcifs.smb.SmbSessionImpl Response command=SMB2_CREATE,status=0,flags=0x0009,mid
=75293,wordCount=0,byteCount=0

...

[2020-10-11 18:04:21,855] TRACE [Transport2] jcifs.util.transport.Transport Socket timeout during peekKey
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:127) ~[?:1.8.0]
        at java.net.SocketInputStream.read(SocketInputStream.java:182) ~[?:1.8.0]
        at java.net.SocketInputStream.read(SocketInputStream.java:152) ~[?:1.8.0]
        at jcifs.util.transport.Transport.readn(Transport.java:70) ~[jcifs-ng-2.1.4-flx.1.jar:?]
        at jcifs.smb.SmbTransportImpl.peekKey(SmbTransportImpl.java:829) ~[jcifs-ng-2.1.4-flx.1.jar:?]
        at jcifs.util.transport.Transport.loop(Transport.java:420) [jcifs-ng-2.1.4-flx.1.jar:?]
        at jcifs.util.transport.Transport.run(Transport.java:779) [jcifs-ng-2.1.4-flx.1.jar:?]
        at java.lang.Thread.run(Thread.java:822) [?:2.9 (07-24-2020)]
[2020-10-11 18:04:21,855] DEBUG [Transport2] jcifs.util.transport.Transport Transport still in use, no idle timeout Transport2[0.0.0.0<00>/X
XX.XXX.XXX.XXX:445,state=3,signingEnforced=true,usage=3]


...


[2020-10-11 18:04:56,891] DEBUG [Transport2] jcifs.util.transport.Transport Transport still in use, no idle timeout Transport2[0.0.0.0<00>/XXX.XXX.XXX.XXX:445,state=3,signingEnforced=true,usage=3]
[2020-10-11 18:05:11,401] TRACE [48035149@qtp--1026970421-0] jcifs.smb.SmbTransportPoolImpl Reusing transport connection Transport2[0.0.0.0<00>/XXX.XXX.XXX.XXX:445,state=3,signingEnforced=true,usage=3]
[2020-10-11 18:05:11,401] TRACE [48035149@qtp--1026970421-0] jcifs.util.transport.Transport Acquire transport 4 Transport2[0.0.0.0<00>/XXX.XXX.XXX.XXX:445,state=3,signingEnforced=true,usage=4]
[2020-10-11 18:05:11,401] TRACE [48035149@qtp--1026970421-0] jcifs.smb.SmbTransportImpl Currently 1 session(s) active for Transport2[0.0.0.0<00>/XXX.XXX.XXX.XXX:445,state=3,signingEnforced=true,usage=4]
[2020-10-11 18:05:11,401] TRACE [48035149@qtp--1026970421-0] jcifs.smb.SmbTransportImpl Reusing existing session SmbSession[credentials=domain\user,targetHost=XXX.XXX.XXX.XXX,targetDomain=null,uid=0,connectionState=2,usage=2]



[2020-10-11 18:05:11,402] TRACE [48035149@qtp--1026970421-0] jcifs.smb.SmbSessionImpl Request [command=SMB2_CREATE,status=0,flags=0x0000,mid=0,wordCount=0,byteCount=0,name=lindy_donoho_000.pst,resolveDfs=false]
[2020-10-11 18:05:11,402] TRACE [48035149@qtp--1026970421-0] jcifs.smb.SmbTransportImpl Sending [command=SMB2_CREATE,status=0,flags=0x0000,mid=0,wordCount=0,byteCount=0,name=lindy_donoho_000.pst,resolveDfs=false]
[2020-10-11 18:05:11,402] TRACE [48035149@qtp--1026970421-0] jcifs.smb.SmbTransportImpl jcifs.internal.smb2.create.Smb2CreateRequest costs 1 avail 512 (Transport2)
[2020-10-11 18:05:11,402] TRACE [48035149@qtp--1026970421-0] jcifs.smb.SmbTransportImpl jcifs.internal.smb2.create.Smb2CloseRequest costs 1 avail 511 (Transport2)
[2020-10-11 18:05:11,402] TRACE [48035149@qtp--1026970421-0] jcifs.smb.SmbTransportImpl Request credits 1
[2020-10-11 18:05:11,402] TRACE [48035149@qtp--1026970421-0] jcifs.smb.SmbTransportImpl Sending [command=SMB2_CREATE,status=0,flags=0x0000,mid=0,wordCount=0,byteCount=0,name=lindy_donoho_000.pst,resolveDfs=false]
[2020-10-11 18:05:11,402] TRACE [48035149@qtp--1026970421-0] jcifs.smb.SmbTransportImpl [command=SMB2_CREATE,status=0,flags=0x0000,mid=75296,wordCount=0,byteCount=96,name=lindy_donoho_000.pst,resolveDfs=false]
[2020-10-11 18:05:11,402] TRACE [48035149@qtp--1026970421-0] jcifs.smb.SmbTransportImpl FE534D4240000000000000000500010008000000A0000000202601000000000000000000010000005500003000800000939326126956D2C18A0789F63B785B7339000000020000000000000000000000000000000000000089001200800000000300000001000000000000007800280000000000000000006C0069006E00640079005F0064006F006E006F0068006F005F003000300030002E00700073007400FE534D424000000000000000060000000C000000000000002126010000000000000000000100000055000030008000008625687292667D78D1D8F7D7835021151800010000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[2020-10-11 18:05:11,403] TRACE [Transport2] jcifs.smb.SmbTransportImpl New data read: Transport2[0.0.0.0<00>/XXX.XXX.XXX.XXX:445,state=3,signingEnforced=true,usage=5]
[2020-10-11 18:05:11,403] TRACE [Transport2] jcifs.smb.SmbTransportImpl FE534D4240000000030200C00500000009000000500000002026010000000000
[2020-10-11 18:05:11,403] DEBUG [Transport2] jcifs.smb.SmbTransportImpl Compound next command 0 read size 80 remain 
[2020-10-11 18:05:11,404] DEBUG [48035149@qtp--1026970421-0] jcifs.smb.SmbTransportImpl Error code: 0xC0000203 for Smb2CreateRequest
[2020-10-11 18:05:11,404] TRACE [48035149@qtp--1026970421-0] jcifs.smb.SmbTransportImpl Adding credits 2
[2020-10-11 18:05:11,404] TRACE [48035149@qtp--1026970421-0] jcifs.smb.SmbSessionImpl Send failed
jcifs.smb.SmbException: An unexpected network error, user session deleted, occurred.
        at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1468) ~[jcifs-ng-2.1.4-flx.1.jar:?]
--
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [jetty-6.1.26.jar:6.1.26]
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228) [jetty-6.1.26.jar:6.1.26]
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582) [jetty-util-6.1.26.jar:6.1.26]
```

**Comment by jmagesh** [comment]
Thanks but unfortunately this doesn't seem to work. We already tried reauthenticating (using pretty much the same code change that you made) but found that no new session was created. The session count just incremented.

So we still get the same "user session deleted" error even after trying your commit (although we did have to change it slightly since the error code is "0xC0000203" not "0xC000203").

Anything else we can try?

**Comment by mbechler** [comment]
Unfortunately I'm running out of ideas. If the log is complete, nothing on our side seems to actively cause the session invalidation. If its a server-side timeout then the behavior is according to the specification, maybe some additional information is revealed by the server logs?

Otherwise you could try to avoid letting the connection idle for this long and see what happens then.

**Comment by jmagesh** [comment]
Thanks for helping us work through this problem, @mbechler.

I think we found out the parameter that sets this timeout on the SMB server:

`HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters\DormantDirectoryTimeout`

https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/role/file-server/

Its default value is 10 minutes and increasing it seems to prevent the user session from being deleted.

**Comment by mbechler** [comment]
Did that setting avoid the issue?

**Comment by jmagesh** [comment]
Yes.

**Comment by tvirtualw** [comment]
For what it's worth, this error can be reproduced as follows:

- Use a SingletonContext.
- In a while loop, create an SmbFile instance to a directory on a share, use listFiles() and for each print the getUncPath() result, then pause for a few seconds. Let this run.
- Meanwhile, go to the Windows server with the file share, go to Computer Management -> System Tools -> Shared Folders -> Sessions and close the session on the server. This reproduces the 0xc0000203 error.

The error code occurs until SingletonContext.getInstance().close() is called. After this close() call, the issue is "fixed".

There is no concurrency involved in the above example. It looks like the connection goes bad, close() removes all connections from the internal transport pool, next call uses fresh connection.

Based on below Microsoft docs, it seems that jcifs should just close/remove the bad connection from the pool when such an error is encountered.

"0xC0000203 STATUS_USER_SESSION_DELETED The user session specified by the client has been deleted on the server. This error is returned by the server if the client sends an incorrect UID."
session: "In Server Message Block (SMB), a persistent-state association between an SMB client and SMB server. A session is tied to the lifetime of the underlying NetBIOS or TCP connection."

This does not help to avoid the issue from happening but would handle it gracefully within the framework.

**Comment by col-panic** [comment]
I can re-enact the problem here. Facing the same problem in a productive setup.

**Comment by mbechler** [comment]
#294 looks good to me. I raised log level to WARNING, as this hopefully is a exceptional situtation and disconnecting the transport is still somewhat invasive (could be shared by other sessions). Still very curious why this error state is reached in regular operation though.

**Comment by col-panic** [comment]
I'm not sure this is exceptional. We have a productive server where we can't change the default user session timeout on idleness, yet the SingletonContext fits quite good. (see https://github.com/elexis/elexis-3-core/blob/master/bundles/ch.elexis.core.jcifs/src/ch/elexis/core/jcifs/SmbURLStreamHandlerService.java for our use of the lib)

So in our scenario this might happen regularly. Closing and opening the SingletonContext on every request would lead to a drammatic drop of performance, and implementing an automatic close and open after n minutes on inactivity seems to be too complicated.

I'm not sure if a log.warn is really required here but ok :)

Thanks for the quick release! Already tested it again, and it works now!

**Comment by mbechler** [comment]
Hope the warning isn't too annoying, but that way it will be much easier to catch potentially related issues.
Still curious what needs to be done to prevent the server from killing the session that harshly (also testing with older windows servers it seems that they actually close the network connection when forcibly killing the session via the console), I would assume that windows/other clients must be doing something different to avoid that.

**Comment by sdonovanuk** [comment]
Greetings. I've just run into the same problem. I have similar instructions to repeat: (i) issue some SMB call (e.g. check file length), then (ii) forcibly kill the user session on the server, and then (iii) attempt a second SMB call -- you'll get the `0xC0000203`.  From above, calling `close()` on the `CIFSContext` appears to be work.  However, IMHO, that shouldn't be necessary.  I can understand any argument that retry logic shouldn't be added, so it should still throw the exception.  But, I think that the `close()` should be called internally -- i.e. a caller of JCIFS shouldn't have to call it.  If useful, I can forward logs.  Many thanks!

**Comment by tvirtualw** [comment]
@sdonovanuk do you get this issue with the latest version still? PR #294  and version 2.1.7 should fix it from briefly looking at the commits. But I haven't tested it myself yet.

**Comment by sdonovanuk** [comment]
@tvirtualw -- now I have to admit I was using the codelibs fork of JCIFS.  However, I just tried jcifs-ng, and indeed, it appears fixed. It: (i) throws a TransportException instead, (ii) appears to close the connection (yay!), and (iii) all subsequent calls work! I'm curious why the different JCIFS forks exist, I'll try and find some history. Thank you!

**Comment by tvirtualw** [comment]
@sdonovanuk my research done a couple of months ago found that codelibs basically tracks jcifs-ng (I just found this extra commit https://github.com/codelibs/jcifs/commit/04297094256be6d97ce4e9bbcfca00b832ca1a91) and it has the legacy jcifs (SMBv1) code as well. So if you need a dependency that is both SMBv1 and SMBv2+ capable, codelibs might be a good choice. Otherwise, I would use jcifs-ng directly to get the latest fixes as quickly as possible.

**Comment by mbechler** [comment]
jcifs-ng also provides both  SMB1 and SMB2+. As you mentioned codelibs  seems to basically track jcifs-ng but has some additional patches, I'm not exactly aware which though.

**Comment by nalesevic** [comment]
Hello everyone. 
I've stumbled upon the similar problem with the `0xC0000203` error message. 

Here are some points:
- Server uses the SMB2 for communication
- I'm using the codelibs `2.1.31` version (lib is forked from jcifs-ng) which contains the #294 PR that handles the NT_STATUS_USER_SESSION_DELETED error, but I'm still getting the exception
- Exception does not occur every time, rather randomly, during the **session setup**

Here is the exception log:
`Caused by: jcifs.smb.SmbException: 0xC0000203
        at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1467)
        at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1578)
        at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1027)
        at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1549)
        at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:557)
        at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:491)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
        at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
        at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
        at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
        at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
        at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
        at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
        at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:573)
        at jcifs.smb.SmbFile.exists(SmbFile.java:873)
        at jcifs.smb.SmbFile.isDirectory(SmbFile.java:1091)`
        
Any help would be very appreciated.

**Comment by danielgp1** [comment]
@nalesevic did you find any solution to your problem?

**Comment by col-panic** [comment]
@danielgp1 do you have this problem? Do you use 2.1.10? Can you provide an updated stacktrace?

**Comment by danielgp1** [comment]
I am using version 2.1.34.
Here is the stacktrace:
`jcifs.smb.SmbException: 0xC0000203
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1496)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1607)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1014)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1578)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:557)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:491)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:573)
	at jcifs.smb.SmbFile.exists(SmbFile.java:873)`

**Comment by col-panic** [comment]
@danielgp1 2.1.34? But not of this project! There is no 2.1.34 version of this project, the newest is 2.1.10 - so you should paste this stacktrace with the correct fork project then!?

**Comment by nicko466** [comment]
I'm currently facing the same issue here with the last version 2.1.10 using smb2

The exception : 
` SmbTreeImpl               Tree disconnect failed
jcifs.smb.SmbException: 0xC0000203
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1496)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1607)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1014)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1578)
	at jcifs.smb.SmbSessionImpl.reauthenticate(SmbSessionImpl.java:772)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:424)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:405)
	at jcifs.smb.SmbTreeImpl.treeDisconnect(SmbTreeImpl.java:844)
	at jcifs.smb.SmbSessionImpl.logoff(SmbSessionImpl.java:1168)
	at jcifs.smb.SmbTransportImpl.doDisconnect(SmbTransportImpl.java:780)
	at jcifs.util.transport.Transport.disconnect(Transport.java:703)
	at jcifs.util.transport.Transport.loop(Transport.java:481)
	at jcifs.util.transport.Transport.run(Transport.java:779)
	at java.lang.Thread.run(Thread.java:750)`

The exception does not occur every time, rather randomly.
