### ISSUE TITLE
Difficulty in providing username and password in URL string

### ISSUE THREAD

**Issue by alankila** [AgNO3/jcifs-ng#3]
I switched to jcifs-ng after learning that this one is supporting large reads out of the box. I used to do this myself by banging into SmbInputStream implementation and overriding the relevant transaction size fields. I need this because without large read support, performance with jcifs is truly atrocious on long-latency links.

However, I ran into trouble with passing authentication data via the smb:// URL. After some experimentation, I discovered that pretty much only this specific form works as a drop-in replacement:

   SmbFile directory = new SmbFile(new URL(null, directoryString, new jcifs.smb.Hanlder());

This used to work with jcifs:

   SmbFile directory = new SmbFile(directoryString);

There were a number of related issues.

Firstly, invoking the jcifs.Config.registerSmbURLHandler() did not seem to work for me, though I did not spend enough time to figure out why. I had to provide the Handler explicitly. I checked that the relevant system property listed the jcifs package, so I really do not understand why new URL() with some smb://-prefixed did fail.

Secondly, the only reason why I was trying the URL-based constructor was that only this specific constructor accepting a single URL parameter appeared to recognize the authentication parameters from the URL and set them up correctly in the config. E.g. the string variant, which I used to have:

   SmbFile directory = new SmbFile(directoryString);

would fail to authenticate. The chain of constructors appear to ignore any URL-passed authentication stuff. I think this is a bug, and that particular String constructor should be changed just invoke this(new URL(null, arg, new jcifs.smb.Handler()), so that at least that one would work like it used to work with jcifs.

**Comment by mbechler** [comment]
I removed the ability to specify username/password in the URL for the new constructors when unifying the authentication as I felt that it was unclear what should actually happen there (NTML vs Kerberos - for Kerberos credential caching would be problematic and encoding the realm in the URL user info would be quite ugly) and that it was preferrable for users to explicitly state what they want.

However, you are right, the legacy SmbFile(String) constructor is calling the wrong constructor for the userInfo to be picked up. Thanks for the report. Fixed in git, will do a release as soon as possible (Monday probably).

With regards to the jcifs.Config.registerSmbURLHandler() problem I don't see either what could be wrong there. Works fine in my test cases. What is happening there? unknown protocol exception?

**Comment by alankila** [comment]
Thanks for the prompt response!

Yes, I got the unknown protocol exception, as if there was no handler for the smb protocol. I do not have time to look into it any further right now, unfortunately.

**Comment by alankila** [comment]
I just tested 1.5.1 and unfortunately this does not resolve the issue. Firstly, the constructor we want invoked is this one:

`
    public SmbFile ( URL url ) {
        this(url, SingletonContext.getInstance().withCredentials(new NtlmPasswordAuthentication(SingletonContext.getInstance(), url.getUserInfo())));
    }
`

The current chain of constructors is, however, like this:

`
    public SmbFile ( String url ) throws MalformedURLException {
        this(url, SingletonContext.getInstance());
    }
`

Which calls:

`
    public SmbFile ( String url, CIFSContext tc ) throws MalformedURLException {
        this(new URL(null, url, tc.getUrlHandler()), tc);
    }
`

which is still ignoring the provided URL user info.

**Comment by mbechler** [comment]
The fix not yet included in 1.5.1, that was released before the fix. Target is 1.5.2, which I hope to release today - maybe tomorrow.

**Comment by alankila** [comment]
Heh yeah, my bad. I saw that 1.5.1 had arrived and just guessed that was the update with the fix. I did not realize it already existed around the time I opened the issue.
